version: '2'
services:

  plateforme:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports: 
      - "3000:80"
      - "443:443"
    command: npm run start
    # container_name: nginx.plateforme.Dockerfile
    depends_on:
    - api-cegid
    - api-plateforme
    volumes:
      - react-plateforme:/plateforme


  api-plateforme:
    build: 
      context: ./api-plateforme
      dockerfile: api.plateforme.Dockerfile
    command: npm run start
    ports: 
      - "4001:4001"
    container_name: api.plateforme.Dockerfile
    depends_on:
    - postgres
    - api-cegid
    volumes:
      - api-plateforme:/api-plateforme


  api-cegid: 
    build: 
      context : ./api-cegid
      dockerfile: api.cegid.Dockerfile
    command: npm run start
    ports: 
      - "5000:5000"
    container_name: api.cegid.Dockerfile

  postgres: 
    image: postgres:14
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - postgres-plateforme:/var/lib/postgresql/data
      - ./db/init.sql:/SQL/plateforme/databaseCreation.sql
      # Cette ligne remplace le script d'initalization de postgres par notre script d'initalisation pour la base de donnée

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=Moncef
      - POSTGRES_DB=plateforme

volumes:
  postgres-plateforme:
    driver: local
  react-plateforme:
    driver: local
  api-plateforme:
    driver: local
  