version: '2'
services:

  plateforme:
    build: 
      context: .
    ports: 
      - "80:80"
      - "443:443"
      - "3000:3000"
    command: npm run start
    container_name: Dockerfile
    depends_on:
    - api-cegid
    - api-plateforme
    volumes:
      - './:/plateforme'


  api-plateforme:
    build: 
      context: ./api-plateforme
    command: npm run start
    ports: 
      - "4001:4001"
    container_name: Dockerfile
    depends_on:
    - postgres
    - api-cegid
    volumes:
      - './:/api-plateforme'


  api-cegid: 
    build: 
      context : ./api-cegid
    command: npm run start
    ports: 
      - "3000:3000"
    container_name: Dockerfile
    volumes:
      - './:/api-cegid'

  postgres: 
    image: postgres:14
    restart: always
    ports: 
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/SQL/plateforme/databaseCreation.sql
      # Cette ligne remplace le script d'initalization de postgres par notre script d'initalisation pour la base de donnée

    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=Moncef
      - POSTGRES_DB=plateforme

volumes:
  db:
    driver: local
  