SELECT TOP 500
GIL_ARTICLE,GIL_CODEARTICLE,
GA_LIBELLE
,SUM(GIL_INVENTAIRE) AS 'Inventaire'
,SUM(GIL_QTEPHOTOINV) AS 'Quantité PhotoInv'
,SUM(GIL_QTESIEGEINV) AS 'Quantité SiegeInv'
, GIL_DEPOT
FROM BNG.dbo.LISTEINVLIG

INNER JOIN ARTICLE ON ARTICLE.GA_CODEARTICLE = GIL_CODEARTICLE
--INNER JOIN DEPOTS ON GIL_DEPOT = DEPOTS.GDE_DEPOT 
--Je ne ramène pas le nom du dépot pour l'instant parce qu'on dirait que la base de donnée n'a pas tout les dépots  

WHERE GIL_CODEARTICLE='00501-0101' AND GIL_SAISIINV='X' 
GROUP BY GIL_ARTICLE,GIL_CODEARTICLE,GIL_DEPOT,GA_LIBELLE
HAVING SUM(GIL_INVENTAIRE)>0
ORDER BY GIL_DEPOT