SELECT TOP 10000
GA_ARTICLE,	GA_CODEARTICLE,
MP2_LIBELLE,MP2_DIM1, MP2_STOCK, MP2_TOTSTOCK

FROM MSUIVISTOCKS
INNER JOIN ARTICLE ON MSUIVISTOCKS.MP2_ARTICLE = ARTICLE.GA_ARTICLE
ORDER BY MP2_TOTSTOCK DESC