/****** Script for SelectTopNRows command from SSMS  ******/
SELECT 
GL_NUMERO,
GL_ETABLISSEMENT,
GL_CODEARTICLE,
GL_DATECREATION,
DATEDIFF(minute,GL_DATECREATION,CURRENT_TIMESTAMP) AS 'Difference',
GL_DATEMODIF

FROM [PMG2015].[dbo].[LIGNE]
WHERE GL_NATUREPIECEG='FFO' AND GL_CODEARTICLE!='FD'
AND DATEDIFF(minute,GL_DATECREATION,CURRENT_TIMESTAMP)<500000

