
-- Requête sans le dernier tarif.
SELECT DISTINCT
GA_CODEARTICLE, 
MAX(a.CC_LIBELLE) AS "marque",MAX(b.CC_LIBELLE) AS "type"
, MAX(GA_LIBELLE) AS "GA_LIBELLE"
, MAX(GA_PVTTC) AS 'GA_PVTTC'
,SUM(GQ_PHYSIQUE-GQ_RESERVECLI+GQ_RESERVEFOU-GQ_PREPACLI) AS 'stock'
, MAX(GA_DATECREATION) as "GA_DATECREATION", MAX(GA_DATEMODIF) as "GA_DATEMODIF"
, [total]= COUNT(*) OVER()
    
FROM DISPO
INNER JOIN ARTICLE ON GA_ARTICLE=GQ_ARTICLE AND GQ_CLOTURE <> 'X' AND GA_TYPEARTICLE = 'MAR' 
LEFT JOIN CHOIXCOD AS a ON a.CC_CODE=GA_FAMILLENIV1
LEFT JOIN CHOIXCOD AS b ON b.CC_CODE=GA_FAMILLENIV2
GROUP BY GA_CODEARTICLE