
-- Requête sans le dernier tarif.
SELECT DISTINCT
GA_CODEARTICLE, 
MAX(CC_LIBELLE) AS "marque",MAX(GA_FAMILLENIV2) AS "Division"
, MAX(GA_LIBELLE) AS "GA_LIBELLE"
, MAX(GA_PVTTC) AS 'GA_PVTTC'
,SUM(GQ_PHYSIQUE-GQ_RESERVECLI+GQ_RESERVEFOU-GQ_PREPACLI) AS 'stock'
, MAX(GA_DATECREATION) as "GA_DATECREATION", MAX(GA_DATEMODIF) as "GA_DATEMODIF"
, [total]= COUNT(*) OVER()
    
FROM DISPO
INNER JOIN ARTICLE ON GA_ARTICLE=GQ_ARTICLE AND GQ_CLOTURE <> 'X' AND GA_TYPEARTICLE = 'MAR' 
LEFT JOIN CHOIXCOD ON CC_CODE=GA_FAMILLENIV1  AND CC_LIBELLE!='Reprise grilles de dimension' 
GROUP BY GA_CODEARTICLE


-- Requête sans le dernier tarif.
SELECT DISTINCT
GA_CODEARTICLE, 
MAX(CC_LIBELLE) AS "marque"
,MAX(GA_FAMILLENIV2) AS "division"
, MAX(GA_LIBELLE) AS "GA_LIBELLE"
, MAX(GA_PVTTC) AS 'GA_PVTTC'
,SUM(GQ_PHYSIQUE-GQ_RESERVECLI+GQ_RESERVEFOU-GQ_PREPACLI) AS 'stock'
, MAX(GA_DATECREATION) as "GA_DATECREATION", MAX(GA_DATEMODIF) as "GA_DATEMODIF"
, [total]= COUNT(*) OVER()
    
FROM DISPO
INNER JOIN ARTICLE ON GA_ARTICLE=GQ_ARTICLE AND GQ_CLOTURE <> 'X' AND GA_TYPEARTICLE = 'MAR' 
LEFT JOIN CHOIXCOD ON CC_CODE=GA_FAMILLENIV1
GROUP BY GA_CODEARTICLE



--Requête avec le dernier tarif


SELECT TOP 1000
GA_CODEARTICLE, 
MAX(a.CC_LIBELLE) AS "marque",MAX(b.CC_LIBELLE) AS "type"
, MAX(GA_LIBELLE) AS "GA_LIBELLE"
, MAX(GA_PVTTC) AS "prixOriginal"
, MAX(GF_PRIXUNITAIRE) AS "prixActuel"
--,SUM(GQ_PHYSIQUE-GQ_RESERVECLI+GQ_RESERVEFOU-GQ_PREPACLI) AS 'stock'
,ISNULL((
    SELECT
    SUM(GQ_PHYSIQUE-GQ_RESERVECLI+GQ_RESERVEFOU-GQ_PREPACLI) QTE_STOCK_NET
    FROM DISPO
    LEFT JOIN ARTICLE AS "ARTICLE2"ON GA_ARTICLE=GQ_ARTICLE AND GQ_CLOTURE <> 'X' AND GA_TYPEARTICLE = 'MAR' 
    WHERE ARTICLE2.GA_CODEARTICLE=ARTICLE.GA_CODEARTICLE
    GROUP BY
    GA_CODEARTICLE
),0) AS 'Stock'
        
, MAX(GA_DATECREATION) as "GA_DATECREATION", MAX(GA_DATEMODIF) as "GA_DATEMODIF"
, [total]= COUNT(*) OVER()
FROM TARIF
LEFT OUTER JOIN TARIFMODE ON TARIF.GF_TARFMODE = TARIFMODE.GFM_TARFMODE 
LEFT OUTER JOIN ARTICLE ON GA_ARTICLE=GF_ARTICLE
--LEFT JOIN DISPO ON GQ_ARTICLE = GA_ARTICLE  AND GQ_CLOTURE <> 'X' AND GA_TYPEARTICLE = 'MAR' 
LEFT JOIN CHOIXCOD AS a ON a.CC_CODE=GA_FAMILLENIV1
LEFT JOIN CHOIXCOD AS b ON b.CC_CODE=GA_FAMILLENIV2
WHERE 
    (GF_REGIMEPRIX = 'TTC' AND ((GA_STATUTART='GEN' or GA_STATUTART='UNI')  
                        AND ( GFM_TYPETARIF IS NULL OR GFM_TYPETARIF IN ('','','001','RETAIL')) AND GF_ARTICLE<>'') 
    AND GFM_NATURETYPE = 'VTE' )
    AND GF_DATEMODIF = ( 
        SELECT MAX(GF_DATEMODIF) FROM TARIF
        WHERE GA_ARTICLE = TARIF.GF_ARTICLE
    )


GROUP BY GA_CODEARTICLE
ORDER BY stock DESC











-- Requête problématique :
-- 1) Impossible de querry le stock
-- 2) Nombre bizarre d'articles (40000 au lieu de 2300)
-- 3) querry lente
set statistics time on
SELECT DISTINCT
GA_CODEARTICLE 
,MAX(a.CC_LIBELLE) AS "marque",MAX(b.CC_LIBELLE) AS "type"
, MAX(GA_LIBELLE) AS "GA_LIBELLE"
, MAX(GA_PVTTC) AS "prixOriginal"
, MAX(GF_PRIXUNITAIRE) AS "prixActuel"
,ISNULL((
    SELECT
    SUM(GQ_PHYSIQUE-GQ_RESERVECLI+GQ_RESERVEFOU-GQ_PREPACLI) QTE_STOCK_NET
    FROM DISPO
    LEFT JOIN ARTICLE AS "ARTICLE2"ON GA_ARTICLE=GQ_ARTICLE AND GQ_CLOTURE <> 'X' AND GA_TYPEARTICLE = 'MAR'  
    WHERE ARTICLE2.GA_CODEARTICLE=ARTICLE.GA_CODEARTICLE
    GROUP BY GA_CODEARTICLE
),0) AS 'stock'

, MAX(GA_DATECREATION) as "GA_DATECREATION", MAX(GA_DATEMODIF) as "GA_DATEMODIF"
, [total]= COUNT(*) OVER()
FROM TARIF
LEFT OUTER JOIN TARIFMODE ON TARIF.GF_TARFMODE = TARIFMODE.GFM_TARFMODE 
LEFT OUTER JOIN ARTICLE ON GA_ARTICLE=GF_ARTICLE
LEFT JOIN CHOIXCOD AS a ON a.CC_CODE=GA_FAMILLENIV1
LEFT JOIN CHOIXCOD AS b ON b.CC_CODE=GA_FAMILLENIV2
WHERE 
    (GF_REGIMEPRIX = 'TTC' AND ((GA_STATUTART='GEN' or GA_STATUTART='UNI')  
                        AND ( GFM_TYPETARIF IS NULL OR GFM_TYPETARIF IN ('','','001','RETAIL')) AND GF_ARTICLE<>'') 
    AND GFM_NATURETYPE = 'VTE' )
    AND GF_DATEMODIF = ( 
        SELECT MAX(GF_DATEMODIF) FROM TARIF
        WHERE GA_ARTICLE = TARIF.GF_ARTICLE
)
${query.where(parametres)} 
GROUP BY GA_CODEARTICLE
${query.having(having)}
${query.sort(parametres)}
${query.paginate(parametres)}
