--ANCIENNE QUERRY qui ne trouvait pas les articles sans tarifs

SELECT DISTINCT
a.CC_LIBELLE AS "marque",b.CC_LIBELLE AS "type",
GA_DATECREATION,GA_LIBELLE,ISNULL(GF_PRIXUNITAIRE, GA_PVTTC) as 'prixActuel', GA_PVTTC as 'prixInitial',
GF_DATEMODIF as 'dernierTarif', GF_LIBELLE as 'descriptionTarif', GF_DATEDEBUT, GF_DATEFIN,
GFM_TYPETARIF, GFM_PERTARIF, GFM_NATURETYPE,
GA2_LIBREARTE

FROM GCTARFCONMODEART  
LEFT JOIN CHOIXCOD AS a ON a.CC_CODE=GA_FAMILLENIV1
LEFT JOIN CHOIXCOD AS b ON b.CC_CODE=GA_FAMILLENIV2    
WHERE 
(GF_REGIMEPRIX = 'TTC' AND ((GA_STATUTART='GEN' or GA_STATUTART='UNI')  
                    AND ( GFM_TYPETARIF IS NULL OR GFM_TYPETARIF IN ('','','001','RETAIL')) AND GF_ARTICLE<>'') 
AND GFM_NATURETYPE = 'VTE' )
AND GF_DATEMODIF = ( 
    SELECT MAX(GF_DATEMODIF) FROM TARIF
    WHERE GCTARFCONMODEART.GA_ARTICLE = TARIF.GF_ARTICLE
)
AND GA_CODEARTICLE = ${parametre}



-- NOUVELLE QUERRY



SELECT DISTINCT
GA_CODEARTICLE
,MAX(a.CC_LIBELLE) AS "marque"
,MAX(b.CC_LIBELLE) AS "type"
,MAX(GA_DATECREATION) AS 'GA_DATECREATION'
,MAX(GA_LIBELLE) AS 'GA_LIBELLE'
,MAX(ISNULL(GF_PRIXUNITAIRE, GA_PVTTC)) as 'prixActuel'
, MAX(GA_PVTTC) as 'prixInitial',
MAX(GF_DATEMODIF) as 'dernierTarif',
GF_LIBELLE as 'descriptionTarif', GF_DATEDEBUT, GF_DATEFIN,
GFM_TYPETARIF, GFM_PERTARIF, GFM_NATURETYPE,
GA2_LIBREARTE

FROM ARTICLE 
LEFT OUTER JOIN TARIF ON TARIF.GF_ARTICLE = ARTICLE.GA_ARTICLE
LEFT OUTER JOIN TARIFMODE ON TARIF.GF_TARFMODE = TARIFMODE.GFM_TARFMODE 
LEFT OUTER JOIN ARTICLECOMPL ON TARIF.GF_ARTICLE = ARTICLECOMPL.GA2_ARTICLE
LEFT OUTER JOIN DIMENSION AS GDI1 ON ARTICLE.GA_GRILLEDIM1 = GDI1.GDI_GRILLEDIM 
    AND ARTICLE.GA_CODEDIM1 = GDI1.GDI_CODEDIM 
    AND GDI1.GDI_TYPEDIM = 'DI1' 
LEFT OUTER JOIN DIMENSION AS GDI2 ON ARTICLE.GA_GRILLEDIM2 = GDI2.GDI_GRILLEDIM 
    AND ARTICLE.GA_CODEDIM2 = GDI2.GDI_CODEDIM 
    AND GDI2.GDI_TYPEDIM = 'DI2' 
LEFT JOIN CHOIXCOD AS a ON a.CC_CODE=GA_FAMILLENIV1
LEFT JOIN CHOIXCOD AS b ON b.CC_CODE=GA_FAMILLENIV2    
WHERE 
 GA_CODEARTICLE = '21016U-01T'
 GROUP BY GA_CODEARTICLE,GF_LIBELLE, GF_DATEDEBUT, GF_DATEFIN,
GFM_TYPETARIF, GFM_PERTARIF, GFM_NATURETYPE,
GA2_LIBREARTE
