SELECT
GDE_LIBELLE,
GQ_DEPOT,
ISNULL(GDI1.GDI_LIBELLE , GDI2.GDI_LIBELLE) AS 'dimension',
SUM(GQ_PHYSIQUE-GQ_RESERVECLI+GQ_RESERVEFOU-GQ_PREPACLI) AS 'stockNet'
    
FROM DISPO
LEFT JOIN ARTICLE ON GA_ARTICLE = GQ_ARTICLE

LEFT OUTER JOIN DIMENSION AS GDI1 ON ARTICLE.GA_GRILLEDIM1 = GDI1.GDI_GRILLEDIM 
AND ARTICLE.GA_CODEDIM1 = GDI1.GDI_CODEDIM 
AND GDI1.GDI_TYPEDIM = 'DI1' 
LEFT OUTER JOIN DIMENSION AS GDI2 ON ARTICLE.GA_GRILLEDIM2 = GDI2.GDI_GRILLEDIM 
AND ARTICLE.GA_CODEDIM2 = GDI2.GDI_CODEDIM 
AND GDI2.GDI_TYPEDIM = 'DI2' 
    
--ATTENTION ! 

--Avec un Left Outer Join on a parfoi des depots avec nom null
--Avec un innerjoin on a des informations de stock parfois fausses
--ENFAITE C'EST PUREMENT DU A LA CLOTURE

--La cloture c'est le résultat du stock avant inventaire, parfois CEGID a besoin de cette info ailleurs. 
--Dans mon cas il faut éliminer du résultat parce que sinon ça fausse tout

INNER JOIN DEPOTS ON GQ_DEPOT = GDE_DEPOT
 AND GA_TYPEARTICLE = 'MAR' AND GQ_CLOTURE <> 'X' AND GA_TYPEARTICLE = 'MAR'

WHERE GA_CODEARTICLE = '875695-400'
    
GROUP BY
GDE_LIBELLE, GDE_ABREGE,
GQ_DEPOT,
GDI1.GDI_LIBELLE , GDI2.GDI_LIBELLE
    
ORDER BY GDE_LIBELLE DESC