SELECT TOP 100
GA_ARTICLE,	GA_CODEARTICLE,
GF_DEVISE, GF_PRIXUNITAIRE, 
GFM_LIBELLE,
/*GQ_AVOIRSTOCK, GQ_STOCKMIN, GQ_STOCKMAX, GQ_STOCKINITIAL*/
GL_LIBELLE, GL_DATELIVRAISON,
GP_TOTALHT, GP_DTSVCREATE,
GPA_ADRESSE1, GPA_ADRESSE2, GPA_ADRESSE3 
FROM ARTICLE
INNER JOIN TARIF ON ARTICLE.GA_ARTICLE = TARIF.GF_ARTICLE
INNER JOIN TARIFMODE ON TARIF.GF_TARFMODE = TARIFMODE.GFM_TARFMODE
/*INNER JOIN DISPO ON DISPO.GQ_ARTICLE = TARIF.GF_ARTICLE*/
INNER JOIN ligne ON ligne.GL_CODEARTICLE = ARTICLE.GA_CODEARTICLE
INNER JOIN PIECE ON PIECE.GP_NUMERO = LIGNE.GL_NUMERO
INNER JOIN PIECEADRESSE ON PIECEADRESSE.GPA_NUMERO = PIECE.GP_NUMERO

/*GROUP BY GA_ARTICLE
ORDER BY GA_DATECREATION DESC
*/