SELECT DISTINCT TOP 100
GA_CODEARTICLE, GA_FAMILLENIV1, GA_DATECREATION,GA_LIBELLE,ISNULL(GF_PRIXUNITAIRE, GA_PVTTC) as 'Prix Actuel', GA_PVTTC as 'Prix Initial',
GF_DATEMODIF as 'Dernière date Tarif', GF_LIBELLE as 'Description Tarif', GF_DATEDEBUT, GF_DATEFIN
GFM_TYPETARIF, GFM_PERTARIF, GFM_NATURETYPE,
GA2_LIBREARTE

FROM GCTARFCONMODEART  
WHERE 
(GF_REGIMEPRIX = 'TTC' AND ((GA_STATUTART='GEN' or GA_STATUTART='UNI')  
					AND ( GFM_TYPETARIF IS NULL OR GFM_TYPETARIF IN ('','','001','RETAIL')) AND GF_ARTICLE<>'') 
AND GFM_NATURETYPE = 'VTE' )
AND GF_DATEMODIF = ( 
	SELECT MAX(GF_DATEMODIF) FROM TARIF
	WHERE GCTARFCONMODEART.GA_ARTICLE = TARIF.GF_ARTICLE
)

--Je peux pas Order By parce que mon pc est lent...
--ORDER BY GA_DATECREATION DESC