SELECT --TOP 1000
GA_ARTICLE,GA_CODEARTICLE,GA_CODEBARRE, GA_FAMILLENIV1,GA_FAMILLENIV2,GA_LIBELLE,
GF_PRIXUNITAIRE, GF_QUALIFPRIX
FROM ARTICLE
INNER JOIN TARIF ON ARTICLE.GA_ARTICLE = TARIF.GF_ARTICLE
--WHERE (GA_CODEARTICLE > @previousScore)
ORDER BY GA_CODEARTICLE
OFFSET 10 ROWS FETCH NEXT 1000 ROWS ONLY;



/*
    Requête avec le stock : Le problème c'est que cette requête est extrêmement lente
    Je crois que le problème c'est que code article n'est pas indexé dans Ligne
*/

  SELECT TOP 500
    GA_ARTICLE,GA_CODEARTICLE,GA_CODEBARRE, GA_FAMILLENIV1,GA_FAMILLENIV2,GA_LIBELLE,
    GF_PRIXUNITAIRE, GF_QUALIFPRIX,
	SUM(GL_QTESTOCK) AS 'Stock Disponible'
    FROM ARTICLE
    INNER JOIN TARIF ON ARTICLE.GA_ARTICLE = TARIF.GF_ARTICLE
	INNER JOIN LIGNE ON LiGNE.GL_CODEARTICLE = ARTICLE.GA_CODEARTICLE 
  WHERE GA_CODEARTICLE='00501-2739' 
  GROUP BY Ga_CODEARTICLE, GA_ARTICLE, GA_CODEBARRE,GA_FAMILLENIV1,GA_FAMILLENIV2,GA_LIBELLE,
    GF_PRIXUNITAIRE, GF_QUALIFPRIX

