--La query est ralentit par le fait qu'on cherche la dernière date de modif
--Mais sans ça on aurait un article pour chaque tarif

SELECT DISTINCT TOP 100
GA_CODEARTICLE, GA_FAMILLENIV1, GA_DATECREATION,GA_LIBELLE,ISNULL(GF_PRIXUNITAIRE, GA_PVTTC) as 'Prix Actuel', GA_PVTTC as 'Prix Initial',
GF_DATEMODIF as 'Dernière date Tarif', GF_LIBELLE as 'Description Tarif', GF_DATEDEBUT, GF_DATEFIN
GFM_TYPETARIF, GFM_PERTARIF, GFM_NATURETYPE,
GA2_LIBREARTE

FROM GCTARFCONMODEART  
WHERE 
(GF_REGIMEPRIX = 'TTC' AND ((GA_STATUTART='GEN' or GA_STATUTART='UNI')  
					AND ( GFM_TYPETARIF IS NULL OR GFM_TYPETARIF IN ('','','001','RETAIL')) AND GF_ARTICLE<>'') 
AND GFM_NATURETYPE = 'VTE' )
AND GF_DATEMODIF = ( 
	SELECT MAX(GF_DATEMODIF) FROM TARIF
	WHERE GCTARFCONMODEART.GA_ARTICLE = TARIF.GF_ARTICLE
)


--Je peux pas Order By parce que mon pc est lent...
--ORDER BY GA_DATECREATION DESC







--La même requête sans tarif, ce qui fait qu'elle est VASTEMENT plus rapide

SELECT TOP 1000

    GA_CODEARTICLE, MAX(GA_FAMILLENIV1),MAX(GA_FAMILLENIV2), MAX(GA_LIBELLE), MAX(GA_PVTTC) AS 'prixInitial', 
    SUM(GQ_PHYSIQUE-GQ_RESERVECLI+GQ_RESERVEFOU-GQ_PREPACLI) AS 'stock'
    , GA_DATECREATION, MAX(GA_DATEMODIF)

FROM DISPO

LEFT JOIN ARTICLE ON GA_ARTICLE=GQ_ARTICLE 
-- LEFT OUTER JOIN DIMENSION AS GDI1 ON ARTICLE.GA_GRILLEDIM1 = GDI1.GDI_GRILLEDIM 
--     AND ARTICLE.GA_CODEDIM1 = GDI1.GDI_CODEDIM 
--     AND GDI1.GDI_TYPEDIM = 'DI1' 
-- LEFT OUTER JOIN DIMENSION AS GDI2 ON ARTICLE.GA_GRILLEDIM2 = GDI2.GDI_GRILLEDIM 
--     AND ARTICLE.GA_CODEDIM2 = GDI2.GDI_CODEDIM 
--     AND GDI2.GDI_TYPEDIM = 'DI2' 

--WHERE GA_CODEARTICLE= ${param}
GROUP BY Ga_CODEARTICLE,GA_DATECREATION


--ORDER BY stock DESC
ORDER BY GA_CODEARTICLE desc