SELECT TOP 1000 
	MP2_CODEARTICLE,
      [MP2_LIBELLE]
      ,SUM([MP2_TOTQTE]) AS 'TOTQTE'
      ,SUM([MP2_STOCK])AS 'STOCK'
      ,SUM([MP2_TOTSTOCK])AS 'TOTSTOCK'
      ,SUM([MP2_TOTQTEDEPOT])AS 'TOTQTEDEPOT'
      ,SUM([MP2_TOTSTOCKDEPOT])AS 'TOTSTOCKDEPOT'
      ,SUM([MP2_TOTQTEDIM1])AS 'TOTQTEDIM1'
  FROM [BNG].[dbo].[MSUIVISTOCKS]
   WHERE MP2_CODEARTICLE like '%00501%'
   GROUP BY 
      [MP2_LIBELLE]
	  ,MP2_CODEARTICLE