--Table Ligne

SELECT TOP 500
	GL_CODEARTICLE,GL_LIBELLE, GL_REFARTBARRE,
	SUM(GL_QTESTOCK) AS 'Stock Disponible'
FROM LIGNE
WHERE GL_CODEARTICLE='00501-2739' 
GROUP BY GL_LIBELLE,GL_CODEARTICLE,GL_REFARTBARRE

--La même requête avec juste le code et le stock
SELECT TOP 500
	GL_CODEARTICLE,
	SUM(GL_QTESTOCK) AS 'Stock Disponible'
FROM LIGNE
WHERE GL_CODEARTICLE='00501-2739' 
GROUP BY GL_CODEARTICLE


-- Table ListeInvLig


SELECT TOP 500
    GIL_ARTICLE,GIL_CODEARTICLE,GA_LIBELLE, GIL_DEPOT
    ,SUM(GIL_INVENTAIRE) AS 'Inventaire'
    ,SUM(GIL_QTEPHOTOINV) AS 'Quantité PhotoInv'
    ,SUM(GIL_QTESIEGEINV) AS 'Quantité SiegeInv'
FROM BNG.dbo.LISTEINVLIG

INNER JOIN ARTICLE ON ARTICLE.GA_CODEARTICLE = GIL_CODEARTICLE
--INNER JOIN DEPOTS ON GIL_DEPOT = DEPOTS.GDE_DEPOT 
--Je ne ramène pas le nom du dépot pour l'instant parce qu'on dirait que la base de donnée n'a pas tout les dépots  

WHERE GIL_CODEARTICLE='00501-0101' AND GIL_SAISIINV='X' 
GROUP BY GIL_ARTICLE,GIL_CODEARTICLE,GIL_DEPOT,GA_LIBELLE
HAVING SUM(GIL_INVENTAIRE)>0
ORDER BY GIL_DEPOT





--Table MSuiviStock

SELECT TOP 500 
	MP2_CODEARTICLE,MP2_LIBELLE
    ,SUM(MP2_TOTQTE) AS 'TotQte'
    ,SUM(MP2_STOCK)AS 'Stock'
    ,SUM(MP2_TOTSTOCK)AS 'TotStock'
    ,SUM(MP2_TOTQTEDEPOT)AS 'TotQTEDepot'
    ,SUM(MP2_TOTSTOCKDEPOT)AS 'TotStockDepot'
    ,SUM(MP2_TOTQTEDIM1)AS 'TotQTEDIM1'
FROM BNG.dbo.MSUIVISTOCKS
WHERE MP2_CODEARTICLE like '%00501%'
GROUP BY MP2_LIBELLE,MP2_CODEARTICLE